server:
  port: ${PORT:8080}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 20MB

  sql:
    init:
      mode: always

  config:
    import: optional:classpath:secrets.properties

groq:
  api:
    key: ${GROQ_API_KEY}